url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Keitt Lab" # the name of your site, e.g. ACME Corp.
description: "The Keitt Lab at the University of Texas at Austin"
